version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      # Install all dependencies (including dependencies for running tests)
      - pip install --upgrade pip
      - pip install -r ./consensus_and_scoring/requirements.txt -t ./consensus_and_scoring
      - rm -rf ./consensus_and_scoring/*.dist-info
  pre_build:
    commands:
      # Discover and run unit tests in the '__tests__' directory
      # Remove all unit tests to reduce the size of the package that will be ultimately uploaded to Lambda
  build:
    commands:
      # Use AWS SAM to package the application by using AWS CloudFormation
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml
artifacts:
  type: zip
  files:
    - template-export.yml
